# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bun.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 640)
        MainWindow.setMinimumSize(QtCore.QSize(960, 640))
        MainWindow.setMaximumSize(QtCore.QSize(960, 640))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(960, 640))
        self.centralwidget.setMaximumSize(QtCore.QSize(960, 640))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(960, 640))
        self.stackedWidget.setMaximumSize(QtCore.QSize(960, 640))
        self.stackedWidget.setObjectName("stackedWidget")
        self.startWindow = QtWidgets.QWidget()
        self.startWindow.setMinimumSize(QtCore.QSize(960, 640))
        self.startWindow.setMaximumSize(QtCore.QSize(960, 640))
        self.startWindow.setObjectName("startWindow")
        self.start = QtWidgets.QPushButton(self.startWindow)
        self.start.setGeometry(QtCore.QRect(720, 340, 160, 62))
        self.start.setStyleSheet("")
        self.start.setText("")
        self.start.setObjectName("start")
        self.how = QtWidgets.QPushButton(self.startWindow)
        self.how.setGeometry(QtCore.QRect(720, 500, 160, 62))
        self.how.setText("")
        self.how.setObjectName("how")
        self.startBackground = QtWidgets.QLabel(self.startWindow)
        self.startBackground.setGeometry(QtCore.QRect(0, 0, 960, 640))
        self.startBackground.setMinimumSize(QtCore.QSize(244, 244))
        self.startBackground.setText("")
        self.startBackground.setPixmap(QtGui.QPixmap("img/background.jpg"))
        self.startBackground.setObjectName("startBackground")
        self.continue_2 = QtWidgets.QPushButton(self.startWindow)
        self.continue_2.setGeometry(QtCore.QRect(720, 420, 160, 62))
        self.continue_2.setText("")
        self.continue_2.setObjectName("continue_2")
        self.title = QtWidgets.QLabel(self.startWindow)
        self.title.setGeometry(QtCore.QRect(120, 50, 679, 207))
        self.title.setText("")
        self.title.setPixmap(QtGui.QPixmap("img/kitbun.png"))
        self.title.setObjectName("title")
        self.snow = QtWidgets.QLabel(self.startWindow)
        self.snow.setGeometry(QtCore.QRect(0, 0, 960, 640))
        self.snow.setText("")
        self.snow.setObjectName("snow")
        self.startBackground.raise_()
        self.snow.raise_()
        self.start.raise_()
        self.title.raise_()
        self.how.raise_()
        self.continue_2.raise_()
        self.stackedWidget.addWidget(self.startWindow)
        self.howTo = QtWidgets.QWidget()
        self.howTo.setMinimumSize(QtCore.QSize(960, 640))
        self.howTo.setMaximumSize(QtCore.QSize(940, 640))
        self.howTo.setObjectName("howTo")
        self.descript = QtWidgets.QLabel(self.howTo)
        self.descript.setGeometry(QtCore.QRect(0, -20, 960, 640))
        self.descript.setText("")
        self.descript.setPixmap(QtGui.QPixmap("img/howTo_1.png"))
        self.descript.setObjectName("descript")
        self.next1 = QtWidgets.QPushButton(self.howTo)
        self.next1.setGeometry(QtCore.QRect(750, 490, 160, 62))
        self.next1.setText("")
        self.next1.setObjectName("next1")
        self.snow2 = QtWidgets.QLabel(self.howTo)
        self.snow2.setGeometry(QtCore.QRect(0, 0, 960, 640))
        self.snow2.setText("")
        self.snow2.setObjectName("snow2")
        self.descript.raise_()
        self.snow2.raise_()
        self.next1.raise_()
        self.stackedWidget.addWidget(self.howTo)
        self.howTo2 = QtWidgets.QWidget()
        self.howTo2.setObjectName("howTo2")
        self.returnbtn3 = QtWidgets.QPushButton(self.howTo2)
        self.returnbtn3.setGeometry(QtCore.QRect(750, 490, 160, 62))
        self.returnbtn3.setText("")
        self.returnbtn3.setObjectName("returnbtn3")
        self.label_17 = QtWidgets.QLabel(self.howTo2)
        self.label_17.setGeometry(QtCore.QRect(0, -20, 960, 640))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("img/howTo_2.png"))
        self.label_17.setObjectName("label_17")
        self.label_17.raise_()
        self.returnbtn3.raise_()
        self.stackedWidget.addWidget(self.howTo2)
        self.mainWindow = QtWidgets.QWidget()
        self.mainWindow.setMinimumSize(QtCore.QSize(960, 640))
        self.mainWindow.setMaximumSize(QtCore.QSize(960, 640))
        self.mainWindow.setObjectName("mainWindow")
        self.label = QtWidgets.QLabel(self.mainWindow)
        self.label.setGeometry(QtCore.QRect(10, 520, 64, 20))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.mainWindow)
        self.label_3.setGeometry(QtCore.QRect(10, 570, 64, 25))
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(self.mainWindow)
        self.progressBar.setGeometry(QtCore.QRect(90, 570, 220, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_2 = QtWidgets.QPushButton(self.mainWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 570, 241, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox = QtWidgets.QGroupBox(self.mainWindow)
        self.groupBox.setGeometry(QtCore.QRect(680, 300, 271, 311))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(30, 70, 101, 16))
        self.label_22.setObjectName("label_22")
        self.redbeanCount = QtWidgets.QLabel(self.groupBox)
        self.redbeanCount.setGeometry(QtCore.QRect(130, 70, 101, 16))
        self.redbeanCount.setObjectName("redbeanCount")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(30, 110, 101, 16))
        self.label_24.setObjectName("label_24")
        self.chouCount = QtWidgets.QLabel(self.groupBox)
        self.chouCount.setGeometry(QtCore.QRect(130, 110, 101, 16))
        self.chouCount.setObjectName("chouCount")
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        self.label_29.setGeometry(QtCore.QRect(30, 230, 101, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(30, 190, 101, 16))
        self.label_30.setObjectName("label_30")
        self.S_redbeanCount = QtWidgets.QSpinBox(self.groupBox)
        self.S_redbeanCount.setGeometry(QtCore.QRect(130, 190, 42, 22))
        self.S_redbeanCount.setPrefix("")
        self.S_redbeanCount.setProperty("value", 0)
        self.S_redbeanCount.setObjectName("S_redbeanCount")
        self.S_chouCount = QtWidgets.QSpinBox(self.groupBox)
        self.S_chouCount.setGeometry(QtCore.QRect(130, 230, 42, 22))
        self.S_chouCount.setObjectName("S_chouCount")
        self.sellbtn = QtWidgets.QPushButton(self.groupBox)
        self.sellbtn.setGeometry(QtCore.QRect(190, 280, 75, 23))
        self.sellbtn.setObjectName("sellbtn")
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setGeometry(QtCore.QRect(20, 280, 101, 16))
        self.label_31.setObjectName("label_31")
        self.profit = QtWidgets.QLabel(self.groupBox)
        self.profit.setGeometry(QtCore.QRect(80, 280, 101, 16))
        self.profit.setObjectName("profit")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 40, 251, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 160, 251, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_5.raise_()
        self.groupBox_6.raise_()
        self.label_22.raise_()
        self.redbeanCount.raise_()
        self.label_24.raise_()
        self.chouCount.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.S_redbeanCount.raise_()
        self.S_chouCount.raise_()
        self.sellbtn.raise_()
        self.label_31.raise_()
        self.profit.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(self.mainWindow)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 490, 241, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(100, 20, 56, 12))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(10, 40, 56, 20))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(10, 20, 56, 12))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(100, 40, 56, 20))
        self.label_40.setObjectName("label_40")
        self.groupBox_3 = QtWidgets.QGroupBox(self.mainWindow)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 641, 481))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 0, 641, 241))
        self.groupBox_7.setObjectName("groupBox_7")
        self.waitLine = QtWidgets.QLabel(self.groupBox_7)
        self.waitLine.setGeometry(QtCore.QRect(0, 30, 401, 190))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.waitLine.setPalette(palette)
        self.waitLine.setText("")
        self.waitLine.setObjectName("waitLine")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setGeometry(QtCore.QRect(440, 10, 191, 101))
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_9)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 171, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_3.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_3.addWidget(self.label_27)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.G_redBeanCount = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.G_redBeanCount.setText("")
        self.G_redBeanCount.setObjectName("G_redBeanCount")
        self.verticalLayout_2.addWidget(self.G_redBeanCount)
        self.G_chouCount = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.G_chouCount.setText("")
        self.G_chouCount.setObjectName("G_chouCount")
        self.verticalLayout_2.addWidget(self.G_chouCount)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setGeometry(QtCore.QRect(450, 130, 61, 16))
        self.label_20.setObjectName("label_20")
        self.T_guestCount = QtWidgets.QLabel(self.groupBox_7)
        self.T_guestCount.setGeometry(QtCore.QRect(540, 130, 31, 16))
        self.T_guestCount.setObjectName("T_guestCount")
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setGeometry(QtCore.QRect(450, 150, 71, 16))
        self.label_25.setObjectName("label_25")
        self.N_guestCount = QtWidgets.QLabel(self.groupBox_7)
        self.N_guestCount.setGeometry(QtCore.QRect(540, 150, 31, 16))
        self.N_guestCount.setObjectName("N_guestCount")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 240, 641, 241))
        self.groupBox_8.setObjectName("groupBox_8")
        self.flour = QtWidgets.QPushButton(self.groupBox_8)
        self.flour.setGeometry(QtCore.QRect(540, 20, 71, 71))
        self.flour.setText("")
        self.flour.setObjectName("flour")
        self.redbean = QtWidgets.QPushButton(self.groupBox_8)
        self.redbean.setGeometry(QtCore.QRect(540, 90, 71, 71))
        self.redbean.setText("")
        self.redbean.setObjectName("redbean")
        self.chou = QtWidgets.QPushButton(self.groupBox_8)
        self.chou.setGeometry(QtCore.QRect(540, 160, 71, 71))
        self.chou.setText("")
        self.chou.setObjectName("chou")
        self.bunLevel = QtWidgets.QPushButton(self.groupBox_8)
        self.bunLevel.setGeometry(QtCore.QRect(235, 140, 51, 71))
        self.bunLevel.setText("")
        self.bunLevel.setObjectName("bunLevel")
        self.baking = QtWidgets.QLabel(self.groupBox_8)
        self.baking.setGeometry(QtCore.QRect(210, 20, 251, 211))
        self.baking.setText("")
        self.baking.setPixmap(QtGui.QPixmap("img/baking.png"))
        self.baking.setScaledContents(True)
        self.baking.setObjectName("baking")
        self.bunLevel_2 = QtWidgets.QPushButton(self.groupBox_8)
        self.bunLevel_2.setGeometry(QtCore.QRect(312, 140, 51, 71))
        self.bunLevel_2.setText("")
        self.bunLevel_2.setObjectName("bunLevel_2")
        self.bunLevel_3 = QtWidgets.QPushButton(self.groupBox_8)
        self.bunLevel_3.setGeometry(QtCore.QRect(385, 140, 51, 71))
        self.bunLevel_3.setText("")
        self.bunLevel_3.setObjectName("bunLevel_3")
        self.bunLevel_4 = QtWidgets.QPushButton(self.groupBox_8)
        self.bunLevel_4.setGeometry(QtCore.QRect(235, 30, 51, 71))
        self.bunLevel_4.setText("")
        self.bunLevel_4.setObjectName("bunLevel_4")
        self.bunLevel_5 = QtWidgets.QPushButton(self.groupBox_8)
        self.bunLevel_5.setGeometry(QtCore.QRect(385, 30, 51, 71))
        self.bunLevel_5.setText("")
        self.bunLevel_5.setObjectName("bunLevel_5")
        self.bunLevel_6 = QtWidgets.QPushButton(self.groupBox_8)
        self.bunLevel_6.setGeometry(QtCore.QRect(312, 30, 51, 71))
        self.bunLevel_6.setText("")
        self.bunLevel_6.setObjectName("bunLevel_6")
        self.baking.raise_()
        self.flour.raise_()
        self.redbean.raise_()
        self.chou.raise_()
        self.bunLevel.raise_()
        self.bunLevel_2.raise_()
        self.bunLevel_3.raise_()
        self.bunLevel_4.raise_()
        self.bunLevel_5.raise_()
        self.bunLevel_6.raise_()
        self.groupBox_8.raise_()
        self.groupBox_7.raise_()
        self.groupBox_4 = QtWidgets.QGroupBox(self.mainWindow)
        self.groupBox_4.setGeometry(QtCore.QRect(680, 40, 271, 261))
        self.groupBox_4.setObjectName("groupBox_4")
        self.seestore = QtWidgets.QLabel(self.groupBox_4)
        self.seestore.setGeometry(QtCore.QRect(10, 20, 240, 240))
        self.seestore.setMinimumSize(QtCore.QSize(240, 240))
        self.seestore.setMaximumSize(QtCore.QSize(240, 240))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.seestore.setPalette(palette)
        self.seestore.setFocusPolicy(QtCore.Qt.TabFocus)
        self.seestore.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seestore.setText("")
        self.seestore.setScaledContents(False)
        self.seestore.setOpenExternalLinks(True)
        self.seestore.setObjectName("seestore")
        self.storeBackground = QtWidgets.QLabel(self.groupBox_4)
        self.storeBackground.setGeometry(QtCore.QRect(10, 20, 240, 240))
        self.storeBackground.setMinimumSize(QtCore.QSize(240, 240))
        self.storeBackground.setText("")
        self.storeBackground.setPixmap(QtGui.QPixmap("img/storeBackground.jpg"))
        self.storeBackground.setObjectName("storeBackground")
        self.storeBackground.raise_()
        self.seestore.raise_()
        self.hour = QtWidgets.QLabel(self.mainWindow)
        self.hour.setGeometry(QtCore.QRect(770, 10, 41, 20))
        self.hour.setObjectName("hour")
        self.minute = QtWidgets.QLabel(self.mainWindow)
        self.minute.setGeometry(QtCore.QRect(810, 10, 31, 20))
        self.minute.setObjectName("minute")
        self.second = QtWidgets.QLabel(self.mainWindow)
        self.second.setGeometry(QtCore.QRect(840, 10, 31, 20))
        self.second.setObjectName("second")
        self.timer = QtWidgets.QLabel(self.mainWindow)
        self.timer.setGeometry(QtCore.QRect(690, 10, 71, 20))
        self.timer.setObjectName("timer")
        self.profit2 = QtWidgets.QLabel(self.mainWindow)
        self.profit2.setGeometry(QtCore.QRect(90, 521, 111, 21))
        self.profit2.setObjectName("profit2")
        self.background2 = QtWidgets.QLabel(self.mainWindow)
        self.background2.setGeometry(QtCore.QRect(0, 0, 951, 611))
        self.background2.setText("")
        self.background2.setPixmap(QtGui.QPixmap("img/main_background.png"))
        self.background2.setObjectName("background2")
        self.background2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.progressBar.raise_()
        self.pushButton_2.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.hour.raise_()
        self.minute.raise_()
        self.second.raise_()
        self.timer.raise_()
        self.profit2.raise_()
        self.stackedWidget.addWidget(self.mainWindow)
        self.upgrade = QtWidgets.QWidget()
        self.upgrade.setMinimumSize(QtCore.QSize(960, 640))
        self.upgrade.setMaximumSize(QtCore.QSize(960, 640))
        self.upgrade.setObjectName("upgrade")
        self.gridLayoutWidget = QtWidgets.QWidget(self.upgrade)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-4, -1, 961, 621))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.upbtn3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.upbtn3.setMinimumSize(QtCore.QSize(240, 0))
        self.upbtn3.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(18)
        self.upbtn3.setFont(font)
        self.upbtn3.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.upbtn3.setObjectName("upbtn3")
        self.gridLayout.addWidget(self.upbtn3, 4, 4, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(24)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(120, 0))
        self.label_11.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(24)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 127);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.upbtn2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.upbtn2.setMinimumSize(QtCore.QSize(240, 0))
        self.upbtn2.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(18)
        self.upbtn2.setFont(font)
        self.upbtn2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.upbtn2.setObjectName("upbtn2")
        self.gridLayout.addWidget(self.upbtn2, 4, 2, 1, 1)
        self.level3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.level3.setMinimumSize(QtCore.QSize(240, 240))
        self.level3.setText("")
        self.level3.setPixmap(QtGui.QPixmap("img/level4.png"))
        self.level3.setObjectName("level3")
        self.gridLayout.addWidget(self.level3, 3, 4, 1, 1)
        self.level1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.level1.setMinimumSize(QtCore.QSize(240, 240))
        self.level1.setMaximumSize(QtCore.QSize(240, 16777215))
        self.level1.setText("")
        self.level1.setPixmap(QtGui.QPixmap("img/level2.png"))
        self.level1.setObjectName("level1")
        self.gridLayout.addWidget(self.level1, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(21)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QLabelhover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 2, 1, 1)
        self.level2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.level2.setMinimumSize(QtCore.QSize(240, 240))
        self.level2.setText("")
        self.level2.setPixmap(QtGui.QPixmap("img/level3.png"))
        self.level2.setScaledContents(True)
        self.level2.setObjectName("level2")
        self.gridLayout.addWidget(self.level2, 3, 2, 1, 1)
        self.lack = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(17)
        self.lack.setFont(font)
        self.lack.setText("")
        self.lack.setObjectName("lack")
        self.gridLayout.addWidget(self.lack, 7, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(120, 0))
        self.label_12.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(24)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(120, 0))
        self.label_13.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(24)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 127);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 2, 1, 1)
        self.upbtn1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.upbtn1.setMinimumSize(QtCore.QSize(240, 0))
        self.upbtn1.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(18)
        self.upbtn1.setFont(font)
        self.upbtn1.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.upbtn1.setObjectName("upbtn1")
        self.gridLayout.addWidget(self.upbtn1, 4, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(21)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QLabelhover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 4, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.upgoldNum = QtWidgets.QLabel(self.gridLayoutWidget)
        self.upgoldNum.setMinimumSize(QtCore.QSize(120, 0))
        self.upgoldNum.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(20)
        self.upgoldNum.setFont(font)
        self.upgoldNum.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 127);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.upgoldNum.setAlignment(QtCore.Qt.AlignCenter)
        self.upgoldNum.setObjectName("upgoldNum")
        self.horizontalLayout_4.addWidget(self.upgoldNum)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(120, 0))
        self.label_15.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(20)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 127);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.gridLayout.addLayout(self.horizontalLayout_4, 8, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(21)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QLabelhover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(120, 0))
        self.label_9.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(24)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(24)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 127);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 4, 1, 1)
        self.returnbtn1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(20)
        self.returnbtn1.setFont(font)
        self.returnbtn1.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.returnbtn1.setObjectName("returnbtn1")
        self.gridLayout.addWidget(self.returnbtn1, 8, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.upgrade)
        self.gridLayout_2.addWidget(self.stackedWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.menu.addAction(self.action_open)
        self.menu.addAction(self.action_save)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "매출 현황"))
        self.label_3.setText(_translate("MainWindow", "평판"))
        self.pushButton_2.setText(_translate("MainWindow", "upgrade"))
        self.label_22.setText(_translate("MainWindow", "팥 붕어빵"))
        self.redbeanCount.setText(_translate("MainWindow", "0개"))
        self.label_24.setText(_translate("MainWindow", "슈크림 붕어빵"))
        self.chouCount.setText(_translate("MainWindow", "0개"))
        self.label_29.setText(_translate("MainWindow", "슈크림 붕어빵"))
        self.label_30.setText(_translate("MainWindow", "팥 붕어빵"))
        self.sellbtn.setText(_translate("MainWindow", "판매"))
        self.label_31.setText(_translate("MainWindow", "예상 수익"))
        self.profit.setText(_translate("MainWindow", "0 GOLD"))
        self.groupBox_5.setTitle(_translate("MainWindow", "보유 붕어빵"))
        self.groupBox_6.setTitle(_translate("MainWindow", "판매 붕어빵"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_37.setText(_translate("MainWindow", "맑음"))
        self.label_38.setText(_translate("MainWindow", "온도:"))
        self.label_39.setText(_translate("MainWindow", "날씨:"))
        self.label_40.setText(_translate("MainWindow", "36도"))
        self.groupBox_7.setTitle(_translate("MainWindow", "손님 화면"))
        self.groupBox_9.setTitle(_translate("MainWindow", "구매수량"))
        self.label_26.setText(_translate("MainWindow", "팥 붕어빵:"))
        self.label_27.setText(_translate("MainWindow", "슈크림 붕어빵:"))
        self.label_20.setText(_translate("MainWindow", "총 손님수:"))
        self.T_guestCount.setText(_translate("MainWindow", "0명"))
        self.label_25.setText(_translate("MainWindow", "대기 손님수:"))
        self.N_guestCount.setText(_translate("MainWindow", "0명"))
        self.groupBox_8.setTitle(_translate("MainWindow", "붕어빵 화면"))
        self.groupBox_4.setTitle(_translate("MainWindow", "현재 가게 외관"))
        self.hour.setText(_translate("MainWindow", "0 시간"))
        self.minute.setText(_translate("MainWindow", "0 분"))
        self.second.setText(_translate("MainWindow", "0 초"))
        self.timer.setText(_translate("MainWindow", "경과시간:"))
        self.profit2.setText(_translate("MainWindow", "0 GOLD"))
        self.upbtn3.setText(_translate("MainWindow", "Upgrade"))
        self.label_10.setText(_translate("MainWindow", "5000"))
        self.label_11.setText(_translate("MainWindow", "GOLD"))
        self.upbtn2.setText(_translate("MainWindow", "Upgrade"))
        self.label_14.setText(_translate("MainWindow", "Level 2"))
        self.label_12.setText(_translate("MainWindow", "5000"))
        self.label_13.setText(_translate("MainWindow", "GOLD"))
        self.upbtn1.setText(_translate("MainWindow", "Upgrade"))
        self.label_16.setText(_translate("MainWindow", "Level 3"))
        self.upgoldNum.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", " GOLD"))
        self.label_4.setText(_translate("MainWindow", "Level 1"))
        self.label_9.setText(_translate("MainWindow", "5000"))
        self.label_8.setText(_translate("MainWindow", "GOLD"))
        self.returnbtn1.setText(_translate("MainWindow", "돌아가기"))
        self.menu.setTitle(_translate("MainWindow", "파일"))
        self.action_save.setText(_translate("MainWindow", "Save(&S)"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_open.setText(_translate("MainWindow", "Load(&L)"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+L"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
